name: CI

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake libgtest-dev

      - name: Build Gtest
        run: |
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp *.a /usr/lib

      - name: Build 
        run: |
          g++ -std=c++20 -O2 -Wall -Wextra -I lab_work lab_work/cli.cpp -o cli
          g++ -std=c++20 -O2 -Wall -Wextra -I lab_work tests/test.cpp -lgtest -lgtest_main -pthread -o test
          
      - name: Run tests
        run: |
          ./test
